export const reducerCases = {
    SET_TOKEN: "SET_TOKEN",
    SET_USER: "SET_USER",
    SET_PLAYLISTS: "SET_PLAYLISTS",
    SET_PLAYING: "SET_PLAYING",
    SET_PLAYER_STATE: "SET_PLAYER_STATE",
    SET_PLAYLIST: "SET_PLAYLIST",
    SET_PLAYLIST_ID: "SET_PLAYLIST_ID",
    SET_NEW_RELEASES: "SET_NEW_RELEASES",
    SET_FEATURED_PLAYLISTS: "SET_FEATURED_PLAYLISTS",
    SET_SEARCH_ARTISTS: "SET_SEARCH_ARTISTS",
  };
  